version: "3.8"

services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  enter-data:
    build: ./enter-data
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - auth-service

  show-results:
    build: ./show-results
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db
      - auth-service

  analytics-service:
    build: ./analytics-service
    depends_on:
      - mysql-db
      - mongo-db

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"

volumes:
  mysql-data:
  mongo-data:
