services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    depends_on:
      mysql-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy

  enter-data:
    build: ./enter-data
    container_name: enter-data
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_started
      mysql-db:
        condition: service_healthy

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      mysql-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy

  show-results:
    build: ./show-results
    container_name: show-results
    ports:
      - "5000:5000"
    depends_on:
      auth-service:
        condition: service_started
      mongo-db:
        condition: service_healthy

volumes:
  mysql_data:
  mongo_data:
